// Copyright 2023 Alexander R. Blanchette

#ifndef PSSP_ENUMS_HPP_20231218_1053
#define PSSP_ENUMS_HPP_20231218_1053
#pragma once

// Standard Library
//   https://en.cppreference.com/w/cpp/standard_library
// std::string
#include <string>
// std::unordered_map
#include <unordered_map>

namespace pssp {
struct trace_info {
  const int col{0};
  const int array_col{0};
  const std::string name{};
  const int type{};
};

const std::unordered_map<std::string, const int> type_map_string{
    {"string", 0}, {"int", 1}, {"float", 2}, {"double", 3}, {"bool", 4}};

// Trick to get the number of fields v
constexpr auto Fields_Start_Line{__LINE__};
enum class Fields {
  depmin,
  depmax,
  odelta,
  resp0,
  resp1,
  resp2,
  resp3,
  resp4,
  resp5,
  resp6,
  resp7,
  resp8,
  resp9,
  stel,
  stdp,
  evel,
  evdp,
  mag,
  user0,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
  dist,
  az,
  baz,
  gcarc,
  depmen,
  cmpaz,
  cmpinc,
  xminimum,
  xmaximum,
  yminimum,
  ymaximum,
  delta,
  b,
  e,
  o,
  a,
  t0,
  t1,
  t2,
  t3,
  t4,
  t5,
  t6,
  t7,
  t8,
  t9,
  f,
  stla,
  stlo,
  evla,
  evlo,
  sb,
  sdelta,
  nzyear,
  nzjday,
  nzhour,
  nzmin,
  nzsec,
  nzmsec,
  nvhdr,
  norid,
  nevid,
  npts,
  nsnpts,
  nwfid,
  nxsize,
  nysize,
  iftype,
  idep,
  iztype,
  iinst,
  istreg,
  ievreg,
  ievtyp,
  iqual,
  isynth,
  imagtyp,
  imagsrc,
  ibody,
  leven,
  lpspol,
  lovrok,
  lcalda,
  kstnm,
  kevnm,
  khole,
  ko,
  ka,
  kt0,
  kt1,
  kt2,
  kt3,
  kt4,
  kt5,
  kt6,
  kt7,
  kt8,
  kt9,
  kf,
  kuser0,
  kuser1,
  kuser2,
  kcmpnm,
  knetwk,
  kdatrd,
  kinst,
  data1,
  data2
};
constexpr auto num_fields{__LINE__ - Fields_Start_Line - 3};
// Trick to get number of fields ^

const std::unordered_map<int, Fields> field_num{// Floats
                                                {0, Fields::depmin},
                                                {1, Fields::depmax},
                                                {2, Fields::odelta},
                                                {3, Fields::resp0},
                                                {4, Fields::resp1},
                                                {5, Fields::resp2},
                                                {6, Fields::resp3},
                                                {7, Fields::resp4},
                                                {8, Fields::resp5},
                                                {9, Fields::resp6},
                                                {10, Fields::resp7},
                                                {11, Fields::resp8},
                                                {12, Fields::resp9},
                                                {13, Fields::stel},
                                                {14, Fields::stdp},
                                                {15, Fields::evel},
                                                {16, Fields::evdp},
                                                {17, Fields::mag},
                                                {18, Fields::user0},
                                                {19, Fields::user1},
                                                {20, Fields::user2},
                                                {21, Fields::user3},
                                                {22, Fields::user4},
                                                {23, Fields::user5},
                                                {24, Fields::user6},
                                                {25, Fields::user7},
                                                {26, Fields::user8},
                                                {27, Fields::user9},
                                                {28, Fields::dist},
                                                {29, Fields::az},
                                                {30, Fields::baz},
                                                {31, Fields::gcarc},
                                                {32, Fields::depmen},
                                                {33, Fields::cmpaz},
                                                {34, Fields::cmpinc},
                                                {35, Fields::xminimum},
                                                {36, Fields::xmaximum},
                                                {37, Fields::yminimum},
                                                {38, Fields::ymaximum},
                                                // Doubles
                                                {39, Fields::delta},
                                                {40, Fields::b},
                                                {41, Fields::e},
                                                {42, Fields::o},
                                                {43, Fields::a},
                                                {44, Fields::t0},
                                                {45, Fields::t1},
                                                {46, Fields::t2},
                                                {47, Fields::t3},
                                                {48, Fields::t4},
                                                {49, Fields::t5},
                                                {50, Fields::t6},
                                                {51, Fields::t7},
                                                {52, Fields::t8},
                                                {53, Fields::t9},
                                                {54, Fields::f},
                                                {55, Fields::stla},
                                                {56, Fields::stlo},
                                                {57, Fields::evla},
                                                {58, Fields::evlo},
                                                {59, Fields::sb},
                                                {60, Fields::sdelta},
                                                // Ints
                                                {61, Fields::nzyear},
                                                {62, Fields::nzjday},
                                                {63, Fields::nzhour},
                                                {64, Fields::nzmin},
                                                {65, Fields::nzsec},
                                                {66, Fields::nzmsec},
                                                {67, Fields::nvhdr},
                                                {68, Fields::norid},
                                                {69, Fields::nevid},
                                                {70, Fields::npts},
                                                {71, Fields::nsnpts},
                                                {72, Fields::nwfid},
                                                {73, Fields::nxsize},
                                                {74, Fields::nysize},
                                                {75, Fields::iftype},
                                                {76, Fields::idep},
                                                {77, Fields::iztype},
                                                {78, Fields::iinst},
                                                {79, Fields::istreg},
                                                {80, Fields::ievreg},
                                                {81, Fields::ievtyp},
                                                {82, Fields::iqual},
                                                {83, Fields::isynth},
                                                {84, Fields::imagtyp},
                                                {85, Fields::imagsrc},
                                                {86, Fields::ibody},
                                                // Bools
                                                {87, Fields::leven},
                                                {88, Fields::lpspol},
                                                {89, Fields::lovrok},
                                                {90, Fields::lcalda},
                                                // Strings
                                                {91, Fields::kstnm},
                                                {92, Fields::kevnm},
                                                {93, Fields::khole},
                                                {94, Fields::ko},
                                                {95, Fields::ka},
                                                {96, Fields::kt0},
                                                {97, Fields::kt1},
                                                {98, Fields::kt2},
                                                {99, Fields::kt3},
                                                {100, Fields::kt4},
                                                {101, Fields::kt5},
                                                {102, Fields::kt6},
                                                {103, Fields::kt7},
                                                {104, Fields::kt8},
                                                {105, Fields::kt9},
                                                {106, Fields::kf},
                                                {107, Fields::kuser0},
                                                {108, Fields::kuser1},
                                                {109, Fields::kuser2},
                                                {110, Fields::kcmpnm},
                                                {111, Fields::knetwk},
                                                {112, Fields::kdatrd},
                                                {113, Fields::kinst},
                                                // Data
                                                {114, Fields::data1},
                                                {115, Fields::data2}};

const std::unordered_map<Fields, trace_info> field_info{
    // Floats
    {Fields::depmin, {0, 0, "DepMin", type_map_string.at("float")}},
    {Fields::depmax, {1, 1, "DepMax", type_map_string.at("float")}},
    {Fields::odelta, {2, 2, "ODelta", type_map_string.at("float")}},
    {Fields::resp0, {3, 3, "Resp0", type_map_string.at("float")}},
    {Fields::resp1, {4, 4, "Resp1", type_map_string.at("float")}},
    {Fields::resp2, {5, 5, "Resp2", type_map_string.at("float")}},
    {Fields::resp3, {6, 6, "Resp3", type_map_string.at("float")}},
    {Fields::resp4, {7, 7, "Resp4", type_map_string.at("float")}},
    {Fields::resp5, {8, 8, "Resp5", type_map_string.at("float")}},
    {Fields::resp6, {9, 9, "Resp6", type_map_string.at("float")}},
    {Fields::resp7, {10, 10, "Resp7", type_map_string.at("float")}},
    {Fields::resp8, {11, 11, "Resp8", type_map_string.at("float")}},
    {Fields::resp9, {12, 12, "Resp9", type_map_string.at("float")}},
    {Fields::stel, {13, 13, "StEl", type_map_string.at("float")}},
    {Fields::stdp, {14, 14, "StDp", type_map_string.at("float")}},
    {Fields::evel, {15, 15, "EvEl", type_map_string.at("float")}},
    {Fields::evdp, {16, 16, "EvDp", type_map_string.at("float")}},
    {Fields::mag, {17, 17, "Mag", type_map_string.at("float")}},
    {Fields::user0, {18, 18, "User0", type_map_string.at("float")}},
    {Fields::user1, {19, 19, "User1", type_map_string.at("float")}},
    {Fields::user2, {20, 20, "User2", type_map_string.at("float")}},
    {Fields::user3, {21, 21, "User3", type_map_string.at("float")}},
    {Fields::user4, {21, 22, "User4", type_map_string.at("float")}},
    {Fields::user5, {23, 23, "User5", type_map_string.at("float")}},
    {Fields::user6, {24, 24, "User6", type_map_string.at("float")}},
    {Fields::user7, {25, 25, "User7", type_map_string.at("float")}},
    {Fields::user8, {26, 26, "User8", type_map_string.at("float")}},
    {Fields::user9, {27, 27, "User9", type_map_string.at("float")}},
    {Fields::dist, {28, 28, "Dist", type_map_string.at("float")}},
    {Fields::az, {29, 29, "Az", type_map_string.at("float")}},
    {Fields::baz, {30, 30, "BAz", type_map_string.at("float")}},
    {Fields::gcarc, {31, 31, "GCArc", type_map_string.at("float")}},
    {Fields::depmen, {32, 32, "DepMen", type_map_string.at("float")}},
    {Fields::cmpaz, {33, 33, "CmpAz", type_map_string.at("float")}},
    {Fields::cmpinc, {34, 34, "CmpInc", type_map_string.at("float")}},
    {Fields::xminimum, {35, 35, "XMinimum", type_map_string.at("float")}},
    {Fields::xmaximum, {36, 36, "XMaximum", type_map_string.at("float")}},
    {Fields::yminimum, {37, 37, "YMinimum", type_map_string.at("float")}},
    {Fields::ymaximum, {38, 38, "YMaximum", type_map_string.at("float")}},
    // Doubles
    {Fields::delta, {39, 0, "Delta", type_map_string.at("double")}},
    {Fields::b, {40, 1, "B", type_map_string.at("double")}},
    {Fields::e, {41, 2, "E", type_map_string.at("double")}},
    {Fields::o, {42, 3, "O", type_map_string.at("double")}},
    {Fields::a, {43, 4, "A", type_map_string.at("double")}},
    {Fields::t0, {44, 5, "T0", type_map_string.at("double")}},
    {Fields::t1, {45, 6, "T1", type_map_string.at("double")}},
    {Fields::t2, {46, 7, "T2", type_map_string.at("double")}},
    {Fields::t3, {47, 8, "T3", type_map_string.at("double")}},
    {Fields::t4, {48, 9, "T4", type_map_string.at("double")}},
    {Fields::t5, {49, 10, "T5", type_map_string.at("double")}},
    {Fields::t6, {50, 11, "T6", type_map_string.at("double")}},
    {Fields::t7, {51, 12, "T7", type_map_string.at("double")}},
    {Fields::t8, {52, 13, "T8", type_map_string.at("double")}},
    {Fields::t9, {53, 14, "T9", type_map_string.at("double")}},
    {Fields::f, {54, 15, "F", type_map_string.at("double")}},
    {Fields::stla, {55, 16, "StLa", type_map_string.at("double")}},
    {Fields::stlo, {56, 17, "StLo", type_map_string.at("double")}},
    {Fields::evla, {57, 18, "EvLa", type_map_string.at("double")}},
    {Fields::evlo, {58, 19, "EvLo", type_map_string.at("double")}},
    {Fields::sb, {59, 20, "sB", type_map_string.at("double")}},
    {Fields::sdelta, {60, 21, "sDelta", type_map_string.at("double")}},
    // Ints
    {Fields::nzyear, {61, 0, "nzYear", type_map_string.at("int")}},
    {Fields::nzjday, {62, 1, "nzJDay", type_map_string.at("int")}},
    {Fields::nzhour, {63, 2, "nzHour", type_map_string.at("int")}},
    {Fields::nzmin, {64, 3, "nzMin", type_map_string.at("int")}},
    {Fields::nzsec, {65, 4, "nzSec", type_map_string.at("int")}},
    {Fields::nzmsec, {66, 5, "nzMSec", type_map_string.at("int")}},
    {Fields::nvhdr, {67, 6, "nVHdr", type_map_string.at("int")}},
    {Fields::norid, {68, 7, "nOrID", type_map_string.at("int")}},
    {Fields::nevid, {69, 8, "nEvID", type_map_string.at("int")}},
    {Fields::npts, {70, 9, "nPts", type_map_string.at("int")}},
    {Fields::nsnpts, {71, 10, "nsnPts", type_map_string.at("int")}},
    {Fields::nwfid, {72, 11, "nWfID", type_map_string.at("int")}},
    {Fields::nxsize, {73, 12, "nXSize", type_map_string.at("int")}},
    {Fields::nysize, {74, 13, "nYSize", type_map_string.at("int")}},
    {Fields::iftype, {75, 14, "iFType", type_map_string.at("int")}},
    {Fields::idep, {76, 15, "iDep", type_map_string.at("int")}},
    {Fields::iztype, {77, 16, "iZType", type_map_string.at("int")}},
    {Fields::iinst, {78, 17, "iInst", type_map_string.at("int")}},
    {Fields::istreg, {79, 18, "iStReg", type_map_string.at("int")}},
    {Fields::ievreg, {80, 19, "iEvReg", type_map_string.at("int")}},
    {Fields::ievtyp, {81, 20, "iEvTyp", type_map_string.at("int")}},
    {Fields::iqual, {82, 21, "iQual", type_map_string.at("int")}},
    {Fields::isynth, {83, 22, "iSynth", type_map_string.at("int")}},
    {Fields::imagtyp, {84, 23, "iMagTyp", type_map_string.at("int")}},
    {Fields::imagsrc, {85, 24, "iMagSrc", type_map_string.at("int")}},
    {Fields::ibody, {86, 25, "iBody", type_map_string.at("int")}},
    // Bools
    {Fields::leven, {87, 0, "lEven", type_map_string.at("bool")}},
    {Fields::lpspol, {88, 1, "lPsPol", type_map_string.at("bool")}},
    {Fields::lovrok, {89, 2, "lOvrOK", type_map_string.at("bool")}},
    {Fields::lcalda, {90, 3, "lCalDA", type_map_string.at("bool")}},
    // Strings
    {Fields::kstnm, {91, 0, "kStNm", type_map_string.at("string")}},
    {Fields::kevnm, {92, 1, "kEvNm", type_map_string.at("string")}},
    {Fields::khole, {93, 2, "kHole", type_map_string.at("string")}},
    {Fields::ko, {94, 3, "kO", type_map_string.at("string")}},
    {Fields::ka, {95, 4, "kA", type_map_string.at("string")}},
    {Fields::kt0, {96, 5, "kT0", type_map_string.at("string")}},
    {Fields::kt1, {97, 6, "kT1", type_map_string.at("string")}},
    {Fields::kt2, {98, 7, "kT2", type_map_string.at("string")}},
    {Fields::kt3, {99, 8, "kT3", type_map_string.at("string")}},
    {Fields::kt4, {100, 9, "kT4", type_map_string.at("string")}},
    {Fields::kt5, {101, 10, "kT5", type_map_string.at("string")}},
    {Fields::kt6, {102, 11, "kT6", type_map_string.at("string")}},
    {Fields::kt7, {103, 12, "kT7", type_map_string.at("string")}},
    {Fields::kt8, {104, 13, "kT8", type_map_string.at("string")}},
    {Fields::kt9, {105, 14, "kT9", type_map_string.at("string")}},
    {Fields::kf, {106, 15, "kF", type_map_string.at("string")}},
    {Fields::kuser0, {107, 16, "kUser0", type_map_string.at("string")}},
    {Fields::kuser1, {108, 17, "kUser1", type_map_string.at("string")}},
    {Fields::kuser2, {109, 18, "kUser2", type_map_string.at("string")}},
    {Fields::kcmpnm, {110, 19, "kCmpNm", type_map_string.at("string")}},
    {Fields::knetwk, {111, 20, "kNetwk", type_map_string.at("string")}},
    {Fields::kdatrd, {112, 21, "kDatRd", type_map_string.at("string")}},
    {Fields::kinst, {113, 22, "kInst", type_map_string.at("string")}},
    // Data
    {Fields::data1, {114, 0, "Data1", type_map_string.at("int")}},
    {Fields::data2, {115, 1, "Data2", type_map_string.at("int")}}};
}  // namespace pssp
#endif
