name: macOS Release Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Prep License file
      run: |
        cp LICENSE License2.txt
        fold -s LICENSE > License.txt

    - name: Configure CMake
      run: cmake --preset gh-ubuntu-release

    - name: Build
      run: cmake --build ${{github.workspace}}/build/release/gh-ubuntu

    - name: Package and checksum
      working-directory: ${{github.workspace}}/build/release/gh-ubuntu
      run: |
        zip PsSp.app.zip PsSp.app
        sha512sum PsSp.app.zip > PsSp.app.zip.sha512

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-13
        path: |
          ${{github.workspace}}/build/release/gh-ubuntu/PsSp.app.zip*
        retention-days: 1
